<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Carbon\Carbon;

class AvailabilityBlock extends Model
{
    use HasFactory;

    protected $fillable = [
        'interviewer_id',
        'date',
        'start_time',
        'end_time',
        'slot_duration_minutes',
    ];

    protected $casts = [
        'date' => 'date',
    ];

    /**
     * Get the interviewer who owns this block.
     */
    public function interviewer(): BelongsTo
    {
        return $this->belongsTo(Interviewer::class);
    }

    /**
     * Get the slots generated by this block.
     */
    public function slots(): HasMany
    {
        return $this->hasMany(Slot::class);
    }

    /**
     * Automated slots slicing orchestrator lifecycle hook.
     */
    protected static function booted()
    {
        static::created(function ($block) {
            $start = Carbon::parse($block->start_time);
            $end = Carbon::parse($block->end_time);
            $duration = $block->slot_duration_minutes;

            $current = clone $start;

            while ($current->copy()->addMinutes($duration)->lte($end)) {
                $slotStart = $current->format('H:i:s');
                $current->addMinutes($duration);
                $slotEnd = $current->format('H:i:s');

                Slot::create([
                    'availability_block_id' => $block->id,
                    'interviewer_id' => $block->interviewer_id,
                    'start_time' => $slotStart,
                    'end_time' => $slotEnd,
                    'status' => 'available',
                ]);
            }
        });
    }
}
